apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo-insecure
spec:
  type: LoadBalancer    # public LB
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

