apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure
  template:
    metadata:
      labels:
        app: insecure
    spec:
      containers:
        - name: app
          image: alpine:3.14
          command: ["sh", "-c", "sleep 3600"]
          securityContext:
            privileged: true   # insecure: privileged container

