apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-insecure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: your-dockerhub-user/insecure-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: demo-config   # insecure: secrets in ConfigMap
          securityContext:
            privileged: true                # insecure
            allowPrivilegeEscalation: true  # insecure
          volumeMounts:
            - name: host-storage
              mountPath: /data
      volumes:
        - name: host-storage
          hostPath:
            path: /var/lib/demo-data   # hostPath -> breakout risk
            type: DirectoryOrCreate

