apiVersion: v1
kind: Service
metadata:
  name: insecure-service
spec:
  type: LoadBalancer  # ❌ expone servicio directamente
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: insecure-pod

