apiVersion: v1
kind: Service
metadata:
  name: insecure-service
spec:
  type: NodePort   # exposes externally
  selector:
    app: insecure
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
