apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
spec:
  containers:
    - name: app
      image: nginx:latest
      securityContext:
        runAsUser: 0           # ❌ Corre como root
        allowPrivilegeEscalation: true # ❌ Permite escalada
      ports:
        - containerPort: 80
      env:
        - name: DB_PASSWORD
          value: "plaintextpassword"  # ❌ Secreto en claro

