name: CI - IaC checks + Lacework (no apply)

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  TF_PLUGIN_CACHE_DIR: /tmp/terraform-cache
  AWS_REGION: eu-west-1   # ajusta si usas otra región
  LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
  LW_SUBACCOUNT_NAME: ${{ secrets.LW_SUBACCOUNT_NAME }} # opcional si usas subcuentas
  LW_API_KEY: ${{ secrets.LW_API_KEY }}
  LW_API_SECRET: ${{ secrets.LW_API_SECRET }}
  
jobs:
  iac-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Checkout old
      if: ${{ matrix.target == 'old' }}
      run: git checkout HEAD^1

    - name: FortiCNAPP analyze (${{ matrix.target }})
      # Recomendación: fija por SHA en producción (ver comentario de seguridad)
      uses: lacework/code-security-action@v1
      with:
        target: ${{ matrix.target }}

