name: FortiCNAPP IaC Scan

on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      - 'kubernetes/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      - 'kubernetes/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  iac-scan:
    name: Lacework FortiCNAPP IaC Scan
    runs-on: ubuntu-24.04

    steps:
      # Step 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2. Prepare environment variables for Docker
      - name: Create environment variables file
        run: |
          echo "Preparing env.list for Lacework/FortiCNAPP IaC scan"
          env | grep "GITHUB_\|LW_\|CI_" > env.list || true
          echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list
          # Optional subaccount
          if [ ! -z "${{ secrets.LW_SUBACCOUNT }}" ]; then
            echo "LW_SUBACCOUNT=${{ secrets.LW_SUBACCOUNT }}" >> env.list
          fi
          # Fail the pipeline if critical findings exist
          echo "EXIT_FLAG=CRITICAL=1" >> env.list
          echo "--- env.list created ---"
          cat env.list | grep -v "SECRET" || true

      # Step 3. (Optional) Debug: show IaC files detected
      - name: List IaC files
        run: |
          echo "Terraform files:"
          find terraform -type f || true
          echo "Kubernetes files:"
          find kubernetes -type f || true

      # Step 4. Run IaC scan using Lacework/FortiCNAPP container
      - name: Run IaC scan
        run: |
          echo "Running Lacework/FortiCNAPP IaC scanner..."
          docker run --rm \
            --env-file env.list \
            -v "$(pwd):/app/src" \
            lacework/codesec:stable \
            lacework iac scan --directory=.

