name: FortiCNAPP IaC Scan

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'kubernetes/**'
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'kubernetes/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
  LW_SUBACCOUNT_NAME: ${{ secrets.LW_SUBACCOUNT_NAME }}
  LW_API_KEY: ${{ secrets.LW_API_KEY }}
  LW_API_SECRET: ${{ secrets.LW_API_SECRET }}

jobs:
  iac-scan:
    name: FortiCNAPP IaC Code Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show directory (debug)
        run: |
          echo "Scanning following directories:"
          ls -R terraform || true
          ls -R kubernetes || true

      # --- Main IaC scan using official Fortinet container ---
      - name: Run FortiCNAPP IaC Scan (PR or Push)
        run: |
          echo "Running FortiCNAPP IaC Code Security container"
          docker run --rm \
            -e LW_ACCOUNT_NAME="${{ secrets.LW_ACCOUNT_NAME }}" \
            -e LW_SUBACCOUNT_NAME="${{ secrets.LW_SUBACCOUNT_NAME }}" \
            -e LW_API_KEY="${{ secrets.LW_API_KEY }}" \
            -e LW_API_SECRET="${{ secrets.LW_API_SECRET }}" \
            -e GITHUB_REF="${GITHUB_REF}" \
            -e GITHUB_REPOSITORY="${GITHUB_REPOSITORY}" \
            -e GITHUB_SHA="${GITHUB_SHA}" \
            -v "${{ github.workspace }}":/scan \
            fortinet/forticnapp-code-security:latest scan /scan

      - name: Upload results to FortiCNAPP (optional for push events)
        if: github.event_name == 'push'
        run: |
          docker run --rm \
            -e LW_ACCOUNT_NAME="${{ secrets.LW_ACCOUNT_NAME }}" \
            -e LW_SUBACCOUNT_NAME="${{ secrets.LW_SUBACCOUNT_NAME }}" \
            -e LW_API_KEY="${{ secrets.LW_API_KEY }}" \
            -e LW_API_SECRET="${{ secrets.LW_API_SECRET }}" \
            -v "${{ github.workspace }}":/scan \
            fortinet/forticnapp-code-security:latest upload /scan

