name: FortiCNAPP Code Security (Push)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

env:
  LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
  LW_API_KEY: ${{ secrets.LW_API_KEY }}
  LW_API_SECRET: ${{ secrets.LW_API_SECRET }}

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: FortiCNAPP analyze push
        uses: lacework/code-security-action@v1
        with:
          target: push

