name: FortiCNAPP IaC Scan

on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      - 'kubernetes/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      - 'kubernetes/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  iac-scan:
    name: Lacework FortiCNAPP IaC Scan
    runs-on: ubuntu-24.04

    steps:
      # Step 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2. Create environment variables file for Docker
      - name: Create environment variables file
        run: |
          echo "Preparing env.list for Lacework/FortiCNAPP IaC scan"
          # Export GH metadata and FortiCNAPP credentials
          env | grep "GITHUB_\|LW_\|CI_" > env.list || true

          echo "LW_ACCOUNT_NAME=${{ secrets.LW_ACCOUNT_NAME }}" >> env.list
          echo "LW_SUBACCOUNT_NAME=${{ secrets.LW_SUBACCOUNT_NAME }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list

          # Fail job if critical findings exist (change to HIGH=1 if desired)
          echo "EXIT_FLAG=CRITICAL=1" >> env.list

          echo "--- env.list created ---"
          cat env.list | grep -v "SECRET" || true

      # Step 3. (Optional) Debug: show IaC files found
      - name: List IaC files
        run: |
          echo "Terraform f

