name: FortiCNAPP IaC Scan

on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      - 'kubernetes/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      - 'kubernetes/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  iac-scan:
    name: Lacework FortiCNAPP IaC Scan
    runs-on: ubuntu-24.04

    steps:
      # Step 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # step 2 - correct permissions  
      - name: Fix permissions for IaC directories
        run: |
          echo "Fixing permissions for terraform and kubernetes directories..."
          sudo chmod -R 777 terraform kubernetes || true        

      # Step 3. Create environment variables file for Docker
      - name: Create environment variables file
        run: |
          echo "Preparing env.list for Lacework/FortiCNAPP IaC scan"
          # Export GH metadata and FortiCNAPP credentials
          env | grep "GITHUB_\|LW_\|CI_" > env.list || true

          echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT_NAME }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list

          # Fail job if critical findings exist (change to HIGH=1 if desired)
          echo "EXIT_FLAG=CRITICAL=1" >> env.list

          echo "--- env.list created ---"
          cat env.list | grep -v "SECRET" || true

      # Step 4. Run IaC scan with official Lacework/FortiCNAPP image
      - name: Run IaC scan
        run: |
          echo "Running Lacework/FortiCNAPP IaC scanner..."
          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh | bash
          docker run --rm \
            --env-file env.list \
            -v "$(pwd):/app/src" \
            lacework/codesec:stable \
            lacework iac scan --directory=. --noninteractive > iac_results.json || true

      # 5️⃣ Subir los resultados como artefacto
      - name: Upload IaC scan report
        uses: actions/upload-artifact@v4
        with:
          name: iac-scan-report
          path: iac_results.json
          retention-days: 7

